### ISSUE TITLE
Support Webpack

### ISSUE THREAD

**Issue by gaearon** [gcanti/flowcheck#7]
I'd like to implement a Webpack [loader](http://webpack.github.io/docs/loaders.html) (read: “transform”) for flowcheck.
Can I consider `transform.js` a part of public API?

**Comment by gcanti** [comment]
Hi!

> I'd like to implement a Webpack loader (read: “transform”) for flowcheck.

It would be really nice.

> Can I consider transform.js a part of public API?

Sure! I was inspired by the public API of react-tools:

https://github.com/facebook/react/blob/master/main.js

Let me know if there's something I can do to help you.

Cheers,
Giulio

**Comment by gaearon** [comment]
I see there's `options.module` and `options.namespace` but I don't quite understand how `module` works or where it is used.

Any way I can make Flowcheck use `require('flowcheck/assert')` instead of `f` global?

**Comment by gcanti** [comment]
The option is there but is not used. It's related to:

https://github.com/gcanti/flowcheck/issues/4

Basically the idea would be to insert at the beginning of the file
an assignment like this

```js
var f = require('flowcheck/assert');
```

where the `namespace` option would override the variable name `f` and the
`module` option would override
the required module allowing to switch to another compatible implementation
of the assert library.
It's not implemented because I have to come up with a good solution to
handle
different module systems: commonjs, amd, etc..

> Any way I can make Flowcheck use require('flowcheck/assert') instead of f
global?

At the moment I'm requiring manually the flowcheck/assert module in my
source files.
But it's something I definitely want to solve in the next few days.
If you have suggestions they are welcomed.

Giulio

p.s.
I think flowcheck could be a great way to bring more people
on the Flow bandwagon since you don't even need to setup Flow to start
using type annotations. Once your code is littered of type annotations,
nothing stops
you to add Flow to your workflow. It's "extreme gradual typing" :)

**Comment by gaearon** [comment]
>I think flowcheck could be a great way to bring more people on the Flow bandwagon since you don't even need to setup Flow to start using type annotations. Once your code is littered of type annotations, nothing stops you to add Flow to your workflow.

Exactly. That's what I liked most about it.

>At the moment I'm requiring manually the flowcheck/assert module in my
source files.

I see. Currently I work around this in flowcheck-loader by using `require('flowcheck/assert')` as `namespace` but that's not very nice :-).
